---
locale: pt
tags: []
layout: input_right
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: 42,1%
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: 0,5%
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: 50%
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Nenhuma das anteriores
  checked: false
name: Jogo de dados
