---
locale: pt
tags: []
layout: input_right
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: 87,5%
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: 60%
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: 0,8%
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: 9,6%
  checked: false
name: Moedas no bolso
